<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Five Men, One Equation – Friction and Flow</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-physics.html" rel="next">
<link href="./03-stokes.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-five-derivations.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Five Men, One Equation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Friction and Flow</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/altustd/navier-stokes-history" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preface</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The World Before Friction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-navier.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Engineer Who Got the Right Answer</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-stokes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">The Cambridge Mathematician</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-five-derivations.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Five Men, One Equation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-physics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">What the Equations Actually Say</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-turbulence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">The Monster Inside the Equations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-millennium.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">A Million Dollars for a Proof</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-a-code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Code Reference</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-list" id="toc-the-list" class="nav-link active" data-scroll-target="#the-list"><span class="header-section-number">5.1</span> The List</a></li>
  <li><a href="#why-this-happens" id="toc-why-this-happens" class="nav-link" data-scroll-target="#why-this-happens"><span class="header-section-number">5.2</span> Why This Happens</a></li>
  <li><a href="#cauchy-and-poisson" id="toc-cauchy-and-poisson" class="nav-link" data-scroll-target="#cauchy-and-poisson"><span class="header-section-number">5.3</span> Cauchy and Poisson</a></li>
  <li><a href="#saint-venants-complaint" id="toc-saint-venants-complaint" class="nav-link" data-scroll-target="#saint-venants-complaint"><span class="header-section-number">5.4</span> Saint-Venant’s Complaint</a></li>
  <li><a href="#what-the-convergence-means" id="toc-what-the-convergence-means" class="nav-link" data-scroll-target="#what-the-convergence-means"><span class="header-section-number">5.5</span> What the Convergence Means</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">5.6</span> Summary</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading"><span class="header-section-number">5.7</span> Further Reading</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Five Men, One Equation</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning Objectives
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Know the five independent derivations of the viscous flow equations and their dates</li>
<li>Understand why simultaneous independent discovery happens in science</li>
<li>Appreciate Saint-Venant’s case and the naming controversy</li>
<li>Recognize what convergence of independent results means about the equations’ validity</li>
</ul>
</div>
</div>
<section id="the-list" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="the-list"><span class="header-section-number">5.1</span> The List</h2>
<p>The Navier-Stokes equations were derived five times, independently, between 1822 and 1845:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 25%">
<col style="width: 29%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th>Author</th>
<th>Country</th>
<th>Method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1822</td>
<td>Claude-Louis Navier</td>
<td>France</td>
<td>Molecular forces</td>
</tr>
<tr class="even">
<td>1828</td>
<td>Augustin-Louis Cauchy</td>
<td>France</td>
<td>Stress tensor (general theory)</td>
</tr>
<tr class="odd">
<td>1829</td>
<td>Siméon Denis Poisson</td>
<td>France</td>
<td>Molecular model, different from Navier’s</td>
</tr>
<tr class="even">
<td>1843</td>
<td>Adhémar Jean Claude Barré de Saint-Venant</td>
<td>France</td>
<td>Continuum, rate of strain</td>
</tr>
<tr class="odd">
<td>1845</td>
<td>George Gabriel Stokes</td>
<td>England</td>
<td>Continuum, stress tensor</td>
</tr>
</tbody>
</table>
<p>The first four are French. The fifth is Irish-born, English-educated, working in England. The time span is twenty-three years. None of the later authors knew the work of all the earlier ones. Saint-Venant in 1843 knew about Navier but disputed his molecular approach; Stokes in 1845 knew about Navier, Cauchy, and Poisson, and cited them.</p>
<p>The five derivations are not minor variations on a theme. They use different mathematical frameworks, different physical starting points, different notations. They arrive at the same equations.</p>
</section>
<section id="why-this-happens" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="why-this-happens"><span class="header-section-number">5.2</span> Why This Happens</h2>
<p>Multiple independent discovery is not as unusual in science as the mythology of individual genius suggests. Newton and Leibniz both invented calculus. Darwin and Wallace both developed natural selection. Oxygen was isolated by Scheele in 1772 and by Priestley in 1774, and the theoretical significance was grasped by neither until Lavoisier in 1777. The radio was developed by Marconi, Tesla, and Lodge in overlapping and disputed sequence.</p>
<p>The pattern is explained by what the historian of science Derek de Solla Price called “the logic of scientific development.” When the tools are available and the problem is pressing, multiple people will find the answer. The tools in 1820 were: Newtonian mechanics, the calculus of variations, Euler’s equations, and a community of trained mathematicians and engineers who knew all of these. The problem was pressing: industry needed viscous flow theory. The answer was constrained: there are only a few mathematical forms that make physical sense.</p>
<p>What makes the Navier-Stokes case remarkable is the number of independent discoverers — five is high — and the speed with which they appeared once Navier had opened the field. Cauchy came six years after Navier; Poisson one year after Cauchy; Saint-Venant and Stokes within two years of each other, both more than a decade after Poisson. The burst in the 1820s reflects the concentration of mathematical talent in Paris; the final pair in the 1840s reflects the maturation of continuum mechanics as a framework.</p>
</section>
<section id="cauchy-and-poisson" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="cauchy-and-poisson"><span class="header-section-number">5.3</span> Cauchy and Poisson</h2>
<p>Augustin-Louis Cauchy is one of the founding figures of mathematical rigor. He produced the first systematic treatment of what we now call real analysis, defining limits and continuity in terms that still appear in undergraduate textbooks. He also, in 1828, published a derivation of the equations of motion for elastic solids and viscous fluids that used the stress tensor as its fundamental object. Cauchy’s derivation was more general than Navier’s — it applied to elastic as well as fluid media — and it placed viscosity in the correct mathematical context.</p>
<p>Siméon Denis Poisson, a year later, used a molecular model similar to Navier’s but more carefully constructed. Where Navier had assumed a specific form for the intermolecular force, Poisson derived more generally what form was consistent with the observed macroscopic behavior of fluids. He arrived at the same viscous term, with additional subtleties about compressibility that were not fully resolved until Stokes.</p>
<p>Both Cauchy and Poisson knew of Navier’s work. Both disputed it on physical grounds while confirming it on mathematical ones. This is the peculiar situation: the equations were confirmed correct by people who disagreed about why they were correct.</p>
</section>
<section id="saint-venants-complaint" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="saint-venants-complaint"><span class="header-section-number">5.4</span> Saint-Venant’s Complaint</h2>
<p>Of all five derivers, the one with the strongest claim to historical neglect is Adhémar Jean Claude Barré de Saint-Venant.</p>
<p>Saint-Venant was born in 1797 and lived to 1886, spanning nearly the entire nineteenth century. He was an engineer, not a pure mathematician, trained at the École Polytechnique and employed for most of his career in the French Corps of Bridges and Roads — the same institution that trained Navier. He made fundamental contributions to elasticity theory, to the theory of torsion in beams, and to the mechanics of plasticity. Any structural engineer who has used Saint-Venant’s principle (that the effect of a localized load becomes uniform at distances large compared to the loading region) has used his work.</p>
<p>In 1843, Saint-Venant published a derivation of the viscous flow equations based on the rate of strain — the rate at which neighboring fluid elements are deforming relative to one another. His approach was, in retrospect, the clearest physical argument of all five: viscous stress is proportional to the rate at which the fluid is shearing, and the coefficient of proportionality is the viscosity. This is exactly the statement that defines a Newtonian fluid, and Saint-Venant made it two years before Stokes.</p>
<p>Saint-Venant spent decades arguing, with characteristic persistence, that the equations should be called the Navier-Saint-Venant equations, or at minimum that his contribution should be recognized alongside Stokes’s. He had a reasonable case. He had the continuum derivation before Stokes, and his physical argument was sound. The mathematical community, to the extent it engaged with the question at all, acknowledged the claim and continued to say “Navier-Stokes.”</p>
<p>Names in science, like names on buildings, do not always go to those who did the most.</p>
</section>
<section id="what-the-convergence-means" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="what-the-convergence-means"><span class="header-section-number">5.5</span> What the Convergence Means</h2>
<p>The five independent derivations are not merely a curiosity. They carry mathematical and physical weight.</p>
<p>When one person derives an equation from one set of assumptions, the result might be an artifact of those assumptions. When five people, using different assumptions and different methods, arrive at the same equation, the likelihood that the result is a mere artifact becomes negligible. The convergence is evidence that the equations are not derived so much as <em>revealed</em> — that they are the inevitable mathematical description of viscous fluid motion under the constraint of Newtonian mechanics.</p>
<p>This kind of convergence is one of the strongest arguments in science. It does not prove the equations correct in any absolute sense — experiment does that — but it argues strongly that any correct equations for viscous flow would have to look like these. The structure is not arbitrary. The viscous term <span class="math inline">\(\mu \nabla^2 \mathbf{u}\)</span> is the only linear, isotropic, second-order correction to the Euler equations that respects the basic symmetries of space and time. Once you decide that viscous effects are linear in the velocity gradient, and that space is isotropic, and that the equations are second-order in space, you have no choice.</p>
<p>Five men found the same door because there was only one door.</p>
</section>
<section id="summary" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="summary"><span class="header-section-number">5.6</span> Summary</h2>
<p>Between 1822 and 1845, five scientists independently derived the equations now called Navier-Stokes. The French quartet — Navier, Cauchy, Poisson, Saint-Venant — worked within the tradition of French rational mechanics. Stokes brought the Cambridge mathematical tradition to bear two years after Saint-Venant. Multiple independent discovery reflects the maturity of the intellectual tools and the pressure of industrial need. Saint-Venant’s claim to recognition was substantively reasonable and historically unsuccessful. The convergence of five independent derivations on the same mathematical structure is itself evidence that the equations are not an artifact of any particular derivation but a fundamental description of viscous flow.</p>
</section>
<section id="further-reading" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="further-reading"><span class="header-section-number">5.7</span> Further Reading</h2>
<ul>
<li>Darrigol, O. <em>Worlds of Flow</em>, Chapter 5. Covers all five derivations and the priority disputes in detail.</li>
<li>Stokes, G.G. “On the theories of the internal friction of fluids in motion.” 1845. Contains Stokes’s own account of his predecessors.</li>
<li>de Solla Price, D. <em>Science Since Babylon</em>. Yale University Press, 1961. The classic treatment of multiple independent discovery and the sociology of scientific progress.</li>
</ul>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-stokes.html" class="pagination-link" aria-label="The Cambridge Mathematician">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">The Cambridge Mathematician</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-physics.html" class="pagination-link" aria-label="What the Equations Actually Say">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">What the Equations Actually Say</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Five Men, One Equation"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">number-sections:</span><span class="co"> true</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>::: {.callout-note icon=false}</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">## Learning Objectives</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Know the five independent derivations of the viscous flow equations and their dates</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Understand why simultaneous independent discovery happens in science</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Appreciate Saint-Venant's case and the naming controversy</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Recognize what convergence of independent results means about the equations' validity</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">## The List</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>The Navier-Stokes equations were derived five times, independently, between 1822 and 1845:</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Year <span class="pp">|</span> Author <span class="pp">|</span> Country <span class="pp">|</span> Method <span class="pp">|</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="pp">|------|--------|---------|--------|</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1822 <span class="pp">|</span> Claude-Louis Navier <span class="pp">|</span> France <span class="pp">|</span> Molecular forces <span class="pp">|</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1828 <span class="pp">|</span> Augustin-Louis Cauchy <span class="pp">|</span> France <span class="pp">|</span> Stress tensor (general theory) <span class="pp">|</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1829 <span class="pp">|</span> Siméon Denis Poisson <span class="pp">|</span> France <span class="pp">|</span> Molecular model, different from Navier's <span class="pp">|</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1843 <span class="pp">|</span> Adhémar Jean Claude Barré de Saint-Venant <span class="pp">|</span> France <span class="pp">|</span> Continuum, rate of strain <span class="pp">|</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1845 <span class="pp">|</span> George Gabriel Stokes <span class="pp">|</span> England <span class="pp">|</span> Continuum, stress tensor <span class="pp">|</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>The first four are French. The fifth is Irish-born, English-educated, working in England. The time span is twenty-three years. None of the later authors knew the work of all the earlier ones. Saint-Venant in 1843 knew about Navier but disputed his molecular approach; Stokes in 1845 knew about Navier, Cauchy, and Poisson, and cited them.</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>The five derivations are not minor variations on a theme. They use different mathematical frameworks, different physical starting points, different notations. They arrive at the same equations.</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why This Happens</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>Multiple independent discovery is not as unusual in science as the mythology of individual genius suggests. Newton and Leibniz both invented calculus. Darwin and Wallace both developed natural selection. Oxygen was isolated by Scheele in 1772 and by Priestley in 1774, and the theoretical significance was grasped by neither until Lavoisier in 1777. The radio was developed by Marconi, Tesla, and Lodge in overlapping and disputed sequence.</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>The pattern is explained by what the historian of science Derek de Solla Price called "the logic of scientific development." When the tools are available and the problem is pressing, multiple people will find the answer. The tools in 1820 were: Newtonian mechanics, the calculus of variations, Euler's equations, and a community of trained mathematicians and engineers who knew all of these. The problem was pressing: industry needed viscous flow theory. The answer was constrained: there are only a few mathematical forms that make physical sense.</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>What makes the Navier-Stokes case remarkable is the number of independent discoverers --- five is high --- and the speed with which they appeared once Navier had opened the field. Cauchy came six years after Navier; Poisson one year after Cauchy; Saint-Venant and Stokes within two years of each other, both more than a decade after Poisson. The burst in the 1820s reflects the concentration of mathematical talent in Paris; the final pair in the 1840s reflects the maturation of continuum mechanics as a framework.</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cauchy and Poisson</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>Augustin-Louis Cauchy is one of the founding figures of mathematical rigor. He produced the first systematic treatment of what we now call real analysis, defining limits and continuity in terms that still appear in undergraduate textbooks. He also, in 1828, published a derivation of the equations of motion for elastic solids and viscous fluids that used the stress tensor as its fundamental object. Cauchy's derivation was more general than Navier's --- it applied to elastic as well as fluid media --- and it placed viscosity in the correct mathematical context.</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>Siméon Denis Poisson, a year later, used a molecular model similar to Navier's but more carefully constructed. Where Navier had assumed a specific form for the intermolecular force, Poisson derived more generally what form was consistent with the observed macroscopic behavior of fluids. He arrived at the same viscous term, with additional subtleties about compressibility that were not fully resolved until Stokes.</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>Both Cauchy and Poisson knew of Navier's work. Both disputed it on physical grounds while confirming it on mathematical ones. This is the peculiar situation: the equations were confirmed correct by people who disagreed about why they were correct.</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="fu">## Saint-Venant's Complaint</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>Of all five derivers, the one with the strongest claim to historical neglect is Adhémar Jean Claude Barré de Saint-Venant.</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>Saint-Venant was born in 1797 and lived to 1886, spanning nearly the entire nineteenth century. He was an engineer, not a pure mathematician, trained at the École Polytechnique and employed for most of his career in the French Corps of Bridges and Roads --- the same institution that trained Navier. He made fundamental contributions to elasticity theory, to the theory of torsion in beams, and to the mechanics of plasticity. Any structural engineer who has used Saint-Venant's principle (that the effect of a localized load becomes uniform at distances large compared to the loading region) has used his work.</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>In 1843, Saint-Venant published a derivation of the viscous flow equations based on the rate of strain --- the rate at which neighboring fluid elements are deforming relative to one another. His approach was, in retrospect, the clearest physical argument of all five: viscous stress is proportional to the rate at which the fluid is shearing, and the coefficient of proportionality is the viscosity. This is exactly the statement that defines a Newtonian fluid, and Saint-Venant made it two years before Stokes.</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>Saint-Venant spent decades arguing, with characteristic persistence, that the equations should be called the Navier-Saint-Venant equations, or at minimum that his contribution should be recognized alongside Stokes's. He had a reasonable case. He had the continuum derivation before Stokes, and his physical argument was sound. The mathematical community, to the extent it engaged with the question at all, acknowledged the claim and continued to say "Navier-Stokes."</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>Names in science, like names on buildings, do not always go to those who did the most.</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="fu">## What the Convergence Means</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>The five independent derivations are not merely a curiosity. They carry mathematical and physical weight.</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>When one person derives an equation from one set of assumptions, the result might be an artifact of those assumptions. When five people, using different assumptions and different methods, arrive at the same equation, the likelihood that the result is a mere artifact becomes negligible. The convergence is evidence that the equations are not derived so much as *revealed* --- that they are the inevitable mathematical description of viscous fluid motion under the constraint of Newtonian mechanics.</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>This kind of convergence is one of the strongest arguments in science. It does not prove the equations correct in any absolute sense --- experiment does that --- but it argues strongly that any correct equations for viscous flow would have to look like these. The structure is not arbitrary. The viscous term $\mu \nabla^2 \mathbf{u}$ is the only linear, isotropic, second-order correction to the Euler equations that respects the basic symmetries of space and time. Once you decide that viscous effects are linear in the velocity gradient, and that space is isotropic, and that the equations are second-order in space, you have no choice.</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>Five men found the same door because there was only one door.</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="fu">## Summary</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>Between 1822 and 1845, five scientists independently derived the equations now called Navier-Stokes. The French quartet --- Navier, Cauchy, Poisson, Saint-Venant --- worked within the tradition of French rational mechanics. Stokes brought the Cambridge mathematical tradition to bear two years after Saint-Venant. Multiple independent discovery reflects the maturity of the intellectual tools and the pressure of industrial need. Saint-Venant's claim to recognition was substantively reasonable and historically unsuccessful. The convergence of five independent derivations on the same mathematical structure is itself evidence that the equations are not an artifact of any particular derivation but a fundamental description of viscous flow.</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a><span class="fu">## Further Reading</span></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Darrigol, O. *Worlds of Flow*, Chapter 5. Covers all five derivations and the priority disputes in detail.</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Stokes, G.G. "On the theories of the internal friction of fluids in motion." 1845. Contains Stokes's own account of his predecessors.</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>de Solla Price, D. *Science Since Babylon*. Yale University Press, 1961. The classic treatment of multiple independent discovery and the sociology of scientific progress.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>